name: Test

on:
  push:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2
      - name: run Docker-Compose & a command inside one of the Compose containers inside the same step
        run: |
          docker-compose -f  ./src/test/docker/docker-compose.yml up -d
          docker ps -a
          docker network ls
          cont=`docker ps -a |grep fusionauth|awk '{print $1}'`
          docker logs $cont
          sleep 10
          echo "finished sleeping"
          docker logs $cont
      - name: Run a one-line script
        run: echo Hello, world!
      #- name: Check to see if FusionAuth is running
        #run: |
          #bash ./src/test/docker/poll-for-kickstart-finish.sh
        #shell: bash
      #- name: Get Applications from FusionAuth
        #run: |
          #curl -H 'Authorization: bf69486b-4733-4470-a592-f1bfce7af580' http://fusionauth:9011/api/application
      #- name: Run a one-line script
        #run: echo Hello, world!
  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: curl stuff
        run: |
          echo "here"
          curl http://172.17.0.1:9011/tmp/logo-white.svg > curl_result_docker.1
          curl http://172.17.0.1:9011/ > curl_result_docker.2
          ls
          cat curl_result_docker.1
          cat curl_result_docker.2
        shell: bash
  destroy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Destroy the FusionAuth instance
        run: docker-compose -f  ./src/test/docker/docker-compose.yml down -v
