name: Test

on:
  push:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - id: test
        uses: mooreds/test-gh-action@v3
